"""Terraform Scaleway defaults for the WAF++ auto-fixer."""
from __future__ import annotations

from wafpass.fix_providers import FixProvider, fix_provider_registry

_TERRAFORM_SCALEWAY_BLOCK_DEFAULTS: dict[tuple[str, str], dict[str, object]] = {
    ("scaleway_instance_server", "tags"): [],
    ("scaleway_instance_server", "enable_ipv6"): False,
    ("scaleway_instance_server", "disable_public_ip"): True,
    ("scaleway_instance_server", "security_group_id"): "",
    ("scaleway_instance_server", "private_network"): {
        "pn_id": "",
        "static_ip": "",
    },
    ("scaleway_instance_server", "additional_volume_ids"): [],
    ("scaleway_instance_ip", "tags"): [],
    ("scaleway_instance_volume", "tags"): [],
    ("scaleway_instance_volume", "size"): 20,
    ("scaleway_instance_volume", "type"): "b_ssd",
    ("scaleway_instance_security_group", "tags"): [],
    ("scaleway_instance_security_group", "inbound_rule"): {
        "action": "accept",
        "protocol": "TCP",
        "port": 443,
        "ip": "0.0.0.0/0",
    },
    ("scaleway_instance_security_group", "outbound_rule"): {
        "action": "accept",
        "protocol": "TCP",
        "port": 443,
        "ip": "0.0.0.0/0",
    },
    ("scaleway_instance_private_nic", "tags"): [],
    ("scaleway_vpc_private_network", "tags"): [],
    ("scaleway_vpc_private_network", "is_endpoints_routing_enabled"): False,
    ("scaleway_vpc_public_gateway", "tags"): [],
    ("scaleway_vpc_public_gateway", "type"): "VPC-GW-S",
    ("scaleway_vpc_public_gateway_dhcp", "tags"): [],
    ("scaleway_vpc_public_gateway_ip", "tags"): [],
    ("scaleway_k8s_cluster", "tags"): [],
    ("scaleway_k8s_cluster", "version"): "1.28",
    ("scaleway_k8s_cluster", "cni"): "cilium",
    ("scaleway_k8s_cluster", "enable_dashboard"): False,
    ("scaleway_k8s_cluster", "private_network_id"): "",
    ("scaleway_k8s_pool", "tags"): [],
    ("scaleway_k8s_pool", "node_type"): "DEV1-M",
    ("scaleway_k8s_pool", "size"): 1,
    ("scaleway_k8s_pool", "min_size"): 1,
    ("scaleway_k8s_pool", "max_size"): 3,
    ("scaleway_rdb_instance", "tags"): [],
    ("scaleway_rdb_instance", "engine"): "PostgreSQL-16",
    ("scaleway_rdb_instance", "is_ha_cluster"): True,
    ("scaleway_rdb_instance", "disable_backup"): False,
    ("scaleway_rdb_instance", "backup_same_region"): False,
    ("scaleway_rdb_instance", "backup_schedule_frequency"): 24,
    ("scaleway_rdb_instance", "backup_schedule_retention"): 7,
    ("scaleway_rdb_read_replica", "tags"): [],
    ("scaleway_rdb_database", "tags"): [],
    ("scaleway_rdb_user", "tags"): [],
    ("scaleway_redis_cluster", "tags"): [],
    ("scaleway_redis_cluster", "version"): "7.0.5",
    ("scaleway_redis_cluster", "cluster_size"): 1,
    ("scaleway_redis_cluster", "node_type"): "RED1-XS",
    ("scaleway_object_bucket", "tags"): [],
    ("scaleway_object_bucket", "versioning"): {},
    ("scaleway_object_bucket", "lifecycle_rule"): {
        "enabled": True,
        "expiration": {"days": 365},
    },
    ("scaleway_object_bucket", "cors_rule"): {
        "allowed_headers": [],
        "allowed_methods": ["GET"],
        "allowed_origins": [],
        "max_age_seconds": 3000,
    },
    ("scaleway_object_bucket_policy", "policy"): "",
    ("scaleway_lb", "tags"): [],
    ("scaleway_lb", "type"): "LB-S",
    ("scaleway_lb", "ssl_compatibility_level"): "ssl_compatibility_level_intermediate",
    ("scaleway_lb_frontend", "tags"): [],
    ("scaleway_lb_backend", "tags"): [],
    ("scaleway_lb_backend", "forward_protocol"): "tcp",
    ("scaleway_lb_backend", "server_timeout"): "5s",
    ("scaleway_iam_api_key", "description"): "Managed by Terraform",
    ("scaleway_iam_application", "description"): "Managed by Terraform",
    ("scaleway_iam_policy", "description"): "Managed by Terraform",
    ("scaleway_iam_user", "tags"): [],
    ("scaleway_domain_record", "ttl"): 3600,
    ("scaleway_domain_record", "data"): "",
    ("scaleway_domain_zone", "tags"): [],
    ("scaleway_container_namespace", "tags"): [],
    ("scaleway_container", "tags"): [],
    ("scaleway_container", "memory_limit"): 128,
    ("scaleway_container", "cpu_limit"): 70,
    ("scaleway_function_namespace", "tags"): [],
    ("scaleway_function", "tags"): [],
    ("scaleway_function", "memory_limit"): 128,
    ("scaleway_function", "cpu_limit"): 70,
    ("scaleway_function", "handler"): "handler.handle",
    ("scaleway_function", "runtime"): "python311",
    ("scaleway_secret", "tags"): [],
    ("scaleway_secret_version", "data"): "",
    ("scaleway_mnq_sqs", "tags"): [],
    ("scaleway_mnq_nats", "tags"): [],
    # Provider-level defaults for provider "scaleway" {} blocks.
    ("scaleway", "region"): "fr-par",
    ("scaleway", "zone"): "fr-par-1",
    ("scaleway", "project_id"): "",
    # Generic tag controls can apply to any Scaleway resource.
    ("*", "tags"): [],
    ("*", "labels"): {},
}


fix_provider_registry.register(
    FixProvider(
        name="terraform_scaleway",
        frameworks=["terraform"],
        providers=["scaleway"],
        block_defaults=_TERRAFORM_SCALEWAY_BLOCK_DEFAULTS,
        resource_type_prefixes=["scaleway_"],
        provider_block_types=["scaleway"],
    )
)
