"""Badge rendering for WAF++ official validations.

This module produces portable validation badges (SVG + JSON) and a lightweight
HTML verification stub. The printable PDF certificate is generated by
wafpass.pdf_reporter.generate_validation_certificate; this module focuses on
small, embeddable assets.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

from wafpass import ValidationEnvelopeSchema


_WAF_LOGO_SVG = """
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
  <rect width="24" height="24" rx="5" fill="#0ea5e9"/>
  <path d="M6 12h4l2-6 2 6h4" stroke="white" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
  <circle cx="17" cy="17" r="2" fill="white"/>
</svg>
"""


def _status_color(status: str) -> tuple[str, str]:
    if status == "official":
        return "#16a34a", "#dcfce7"  # green-600, green-100
    if status == "offline":
        return "#ca8a04", "#fef9c3"  # yellow-600, yellow-100
    return "#64748b", "#f1f5f9"      # slate-500, slate-100


def _short_hash(run_hash: str) -> str:
    return f"{run_hash[:8]}…{run_hash[-8:]}"


def _result_dict(envelope: ValidationEnvelopeSchema) -> dict | None:
    if isinstance(envelope.result, dict):
        return envelope.result
    return envelope.result.model_dump() if envelope.result else None


def generate_badge_svg(
    envelope: ValidationEnvelopeSchema,
    badge_json: dict[str, Any] | None = None,
) -> str:
    """Generate an embeddable SVG badge for a validation envelope."""
    result_dict = _result_dict(envelope)
    status = envelope.status
    label = "WAF++ Validated" if status == "official" else "WAF++ Offline"
    score = result_dict.get("score") if result_dict else None
    score_text = f"{score}%" if score is not None else "—"
    run_hash = _short_hash(envelope.run_hash)

    sv = envelope.server_validation
    verification_url = ""
    if sv:
        verification_url = sv.verification_url
    elif badge_json:
        verification_url = badge_json.get("verification_url", "")

    text_color, bg_color = _status_color(status)

    # Compute rough widths based on text lengths.
    label_width = max(180, len(label) * 9 + 60)
    score_width = 70
    hash_width = max(200, len(run_hash) * 8 + 40)
    total_width = label_width + score_width + hash_width + 70  # logo + spacing

    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" width="{total_width}" height="32" viewBox="0 0 {total_width} 32"
     role="img" aria-label="{label}: {score_text} ({run_hash})"
     style="font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; font-size: 12px;">
  <defs>
    <linearGradient id="labelBg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="{bg_color}"/>
      <stop offset="100%" stop-color="#ffffff"/>
    </linearGradient>
  </defs>
  <rect x="0" y="0" width="{total_width}" height="32" rx="6" fill="#f8fafc" stroke="#e2e8f0" stroke-width="1"/>
  <g transform="translate(8, 4)">
    {_WAF_LOGO_SVG.strip()}
  </g>
  <rect x="38" y="1" width="{label_width}" height="30" fill="url(#labelBg)"/>
  <text x="{38 + label_width // 2}" y="17" text-anchor="middle" fill="{text_color}" font-weight="600">{label}</text>
  <rect x="{38 + label_width}" y="1" width="{score_width}" height="30" fill="{text_color}"/>
  <text x="{38 + label_width + score_width // 2}" y="17" text-anchor="middle" fill="white" font-weight="700">{score_text}</text>
  <rect x="{38 + label_width + score_width}" y="1" width="{hash_width}" height="30" fill="#f1f5f9"/>
  <text x="{38 + label_width + score_width + 8}" y="17" fill="#475569" font-family="monospace" font-size="10px">{run_hash}</text>
'''
    if verification_url:
        svg += f'  <a href="{verification_url}" target="_blank" rel="noopener"><rect x="0" y="0" width="{total_width}" height="32" fill="transparent"/></a>\n'

    svg += "</svg>\n"
    return svg.strip()


def generate_validation_html_stub(envelope: ValidationEnvelopeSchema) -> str:
    """Generate a small HTML verification snippet that can be embedded in pages."""
    result_dict = _result_dict(envelope)
    status = envelope.status
    sv = envelope.server_validation
    badge = {
        "status": status,
        "score": result_dict.get("score") if result_dict else None,
        "run_hash": envelope.run_hash,
        "validation_id": sv.validation_id if sv else None,
        "verification_url": sv.verification_url if sv else "",
    }

    status_color = "green" if status == "official" else "goldenrod"
    return f"""
<div style="font-family:system-ui,Arial,sans-serif;max-width:480px;border:1px solid #e2e8f0;border-radius:8px;padding:16px;background:#fff;">
  <div style="display:flex;align-items:center;gap:10px;">
    {_WAF_LOGO_SVG.strip()}
    <span style="font-weight:700;font-size:18px;color:#0f172a;">WAF++ Validation</span>
  </div>
  <hr style="border:none;border-top:1px solid #e2e8f0;margin:12px 0;">
  <p style="margin:4px 0;font-size:14px;">
    Status: <span style="color:{status_color};font-weight:700;text-transform:uppercase;">{status}</span>
  </p>
  <p style="margin:4px 0;font-size:14px;">Score: <strong>{badge['score'] or '—'}%</strong></p>
  <p style="margin:4px 0;font-size:12px;color:#64748b;font-family:monospace;">Run hash: {badge['run_hash']}</p>
  {f'<p style="margin:4px 0;font-size:12px;color:#64748b;font-family:monospace;">Validation ID: {badge["validation_id"]}</p>' if badge['validation_id'] else ''}
  {f'<a href="{badge["verification_url"]}" target="_blank" rel="noopener" style="display:inline-block;margin-top:8px;padding:6px 12px;background:#0ea5e9;color:#fff;border-radius:4px;text-decoration:none;font-size:13px;">Verify online</a>' if badge['verification_url'] else ''}
</div>
""".strip()
