"""Interactive wizard for ``wafpass control generate``.

Guides the user through 7 steps to author a new WAF++ control:
  1. Describe the requirement
  2. Classify the control (id, pillar, severity, type)
  3. Define checks
  4. Preview and edit (YAML + $EDITOR)
  5. Validate against Pydantic schema
  6. Export (YAML control + Checkov stub)
  7. Push to wafpass-server (optional)

All I/O uses plain ``input()`` — no heavy TUI dependencies.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

import yaml
from pydantic import ValidationError
from rich.console import Console
from rich.panel import Panel
from rich.syntax import Syntax

from wafpass.control_schema import (
    ENGINES,
    PILLAR_TO_PREFIX,
    PILLARS,
    SEVERITIES,
    TYPES,
    WizardCheck,
    WizardControl,
)

console = Console()

_HEADER_COMMENT = (
    "# Generated by wafpass control generate — do not edit manually\n"
    "# Source: {id} | Pillar: {pillar} | Severity: {severity}\n"
)

# ── Prompt helpers ────────────────────────────────────────────────────────────


def _echo(msg: str) -> None:
    console.print(msg)


def _prompt(label: str, default: str = "") -> str:
    """Read a non-empty line from the user."""
    hint = f" [{default}]" if default else ""
    while True:
        try:
            raw = input(f"  {label}{hint}: ").strip()
        except (EOFError, KeyboardInterrupt):
            _echo("\n[yellow]Aborted.[/yellow]")
            sys.exit(0)
        value = raw or default
        if value:
            return value
        _echo("  [red]Value is required.[/red]")


def _select(label: str, options: list[str], default: str | None = None) -> str:
    """Numbered menu selection."""
    _echo(f"\n  {label}")
    for i, opt in enumerate(options, 1):
        marker = " (default)" if opt == default else ""
        _echo(f"    [{i}] {opt}{marker}")
    hint = f" [1-{len(options)}]"
    if default and default in options:
        hint += f" (Enter for '{default}')"
    while True:
        try:
            raw = input(f"  Choice{hint}: ").strip()
        except (EOFError, KeyboardInterrupt):
            _echo("\n[yellow]Aborted.[/yellow]")
            sys.exit(0)
        if not raw and default:
            return default
        try:
            idx = int(raw)
            if 1 <= idx <= len(options):
                return options[idx - 1]
        except ValueError:
            # Allow typing the value directly
            if raw.lower() in [o.lower() for o in options]:
                return next(o for o in options if o.lower() == raw.lower())
        _echo(f"  [red]Enter a number between 1 and {len(options)}.[/red]")


def _multi_select(label: str, options: list[str]) -> list[str]:
    """Comma-separated or space-separated multi-select."""
    _echo(f"\n  {label}")
    for i, opt in enumerate(options, 1):
        _echo(f"    [{i}] {opt}")
    _echo("  Enter numbers separated by commas (e.g. 1,3):")
    while True:
        try:
            raw = input("  Choices: ").strip()
        except (EOFError, KeyboardInterrupt):
            _echo("\n[yellow]Aborted.[/yellow]")
            sys.exit(0)
        if not raw:
            _echo("  [red]Select at least one option.[/red]")
            continue
        selected: list[str] = []
        valid = True
        for part in raw.replace(" ", ",").split(","):
            part = part.strip()
            if not part:
                continue
            try:
                idx = int(part)
                if 1 <= idx <= len(options):
                    selected.append(options[idx - 1])
                else:
                    _echo(f"  [red]Invalid choice: {part}[/red]")
                    valid = False
                    break
            except ValueError:
                if part.lower() in [o.lower() for o in options]:
                    selected.append(next(o for o in options if o.lower() == part.lower()))
                else:
                    _echo(f"  [red]Unknown option: {part}[/red]")
                    valid = False
                    break
        if valid and selected:
            return list(dict.fromkeys(selected))  # deduplicate, preserve order
        if not selected:
            _echo("  [red]Select at least one option.[/red]")


def _confirm(label: str, default: bool = True) -> bool:
    hint = "[Y/n]" if default else "[y/N]"
    try:
        raw = input(f"  {label} {hint}: ").strip().lower()
    except (EOFError, KeyboardInterrupt):
        _echo("\n[yellow]Aborted.[/yellow]")
        sys.exit(0)
    if not raw:
        return default
    return raw in ("y", "yes")


# ── ID suggestion ─────────────────────────────────────────────────────────────


def _suggest_id(pillar: str, controls_dir: Path) -> str:
    """Return the next available <PREFIX>-NNN id for the given pillar."""
    prefix = PILLAR_TO_PREFIX.get(pillar, pillar.upper()[:3])
    existing_nums: list[int] = []

    if controls_dir.exists():
        for yml_path in controls_dir.rglob("*.yml"):
            stem = yml_path.stem.upper()
            if stem.startswith(prefix + "-"):
                tail = stem[len(prefix) + 1 :]
                if tail.isdigit():
                    existing_nums.append(int(tail))

    next_num = (max(existing_nums) + 1) if existing_nums else 1
    return f"{prefix}-{next_num:03d}"


# ── YAML rendering ────────────────────────────────────────────────────────────


def _control_to_yaml(control: WizardControl) -> str:
    """Render a WizardControl as a clean YAML string (no Python object tags)."""
    data: dict[str, Any] = {
        "id": control.id,
        "pillar": control.pillar,
        "severity": control.severity,
        "type": list(control.type),
        "description": control.description.strip() + "\n",
        "checks": [
            {
                "id": ch.id,
                "engine": ch.engine,
                "description": ch.description.strip(),
                "expected": ch.expected.strip(),
            }
            for ch in control.checks
        ],
    }
    # Use default_flow_style=False and allow_unicode for readable output
    body = yaml.dump(
        data,
        default_flow_style=False,
        allow_unicode=True,
        sort_keys=False,
        width=88,
    )
    header = _HEADER_COMMENT.format(
        id=control.id, pillar=control.pillar, severity=control.severity
    )
    return header + body


# ── Checkov stub generation ───────────────────────────────────────────────────

_RESOURCE_HINTS: dict[str, list[str]] = {
    "network": [
        "aws_security_group",
        "aws_vpc",
        "azurerm_network_security_group",
        "google_compute_firewall",
    ],
    "identity": [
        "aws_iam_role",
        "aws_iam_policy",
        "azurerm_role_assignment",
    ],
    "data": [
        "aws_s3_bucket",
        "aws_db_instance",
        "azurerm_storage_account",
        "google_storage_bucket",
    ],
    "cost": [
        "aws_instance",
        "aws_eks_node_group",
        "azurerm_virtual_machine",
    ],
}


def _infer_supported_resources(control: WizardControl) -> list[str]:
    """Heuristic: map control types to typical Terraform resource types."""
    resources: list[str] = []
    for t in control.type:
        resources.extend(_RESOURCE_HINTS.get(t, []))
    return list(dict.fromkeys(resources)) or ["*"]


def _checkov_class_name(control_id: str) -> str:
    """Convert 'SOV-011' → 'CheckSov011'."""
    return "Check" + control_id.replace("-", "").title().replace(" ", "")


def _checkov_check_id(control_id: str) -> str:
    """Convert 'SOV-011' → 'CKV_SOV_011'."""
    return "CKV_" + control_id.replace("-", "_")


def _generate_checkov_stub(control: WizardControl) -> str:
    """Return the content of a Checkov custom check Python stub."""
    class_name = _checkov_class_name(control.id)
    check_id = _checkov_check_id(control.id)
    supported = _infer_supported_resources(control)
    supported_repr = "[" + ", ".join(f'"{r}"' for r in supported) + "]"

    # Truncate description for the class name field if very long
    short_desc = control.description.strip().split("\n")[0][:120]

    header = _HEADER_COMMENT.format(
        id=control.id, pillar=control.pillar, severity=control.severity
    )

    return f'''{header}
"""
WAF++ Control: {control.id} ({control.pillar} / {control.severity})

Auto-generated Checkov custom check stub.
Implements: {short_desc}

Do NOT edit the header lines above.  Implement check logic in
``scan_resource_conf`` and remove the NotImplementedError.
"""

from checkov.common.models.enums import CheckCategories, CheckResult
from checkov.terraform.checks.resource.base_resource_check import BaseResourceCheck


class {class_name}(BaseResourceCheck):
    """WAF++ Control {control.id}: {short_desc}"""

    def __init__(self) -> None:
        name = "{short_desc}"
        check_id = "{check_id}"
        categories = [CheckCategories.GENERAL_SECURITY]
        supported_resources = {supported_repr}
        super().__init__(
            name=name,
            check_id=check_id,
            categories=categories,
            supported_resources=supported_resources,
        )

    def scan_resource_conf(self, conf: dict) -> CheckResult:
        # TODO: implement check logic for WAF++ control {control.id}
        # Expected: {control.checks[0].expected if control.checks else "see control YAML"}
        raise NotImplementedError(
            "This stub was generated by wafpass control generate. "
            "Implement check logic for WAF++ control {control.id}."
        )


scanner = {class_name}()
'''


# ── Export ────────────────────────────────────────────────────────────────────


def export_control(
    control: WizardControl,
    controls_dir: Path,
    checkov_dir: Path,
) -> tuple[Path, Path]:
    """Write the control YAML and Checkov stub.  Return (yaml_path, py_path)."""
    # Target 1 — controls/<pillar>/<id>.yml
    pillar_dir = controls_dir / control.pillar
    pillar_dir.mkdir(parents=True, exist_ok=True)
    yaml_path = pillar_dir / f"{control.id}.yml"
    yaml_path.write_text(_control_to_yaml(control), encoding="utf-8")

    # Target 2 — checkov_checks/<id>.py
    checkov_dir.mkdir(parents=True, exist_ok=True)
    py_path = checkov_dir / f"{control.id}.py"
    py_path.write_text(_generate_checkov_stub(control), encoding="utf-8")

    return yaml_path, py_path


# ── Server push ───────────────────────────────────────────────────────────────


def push_to_server(control: WizardControl, server_url: str) -> bool:
    """POST the control payload to ``<server_url>/controls``.

    Returns True on success.  Warns and returns False on any error so that
    the caller can continue — files are already written by this point.
    """
    url = server_url.rstrip("/") + "/controls"
    payload = control.model_dump()
    body = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=body,
        method="POST",
        headers={"Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            status = resp.status
    except urllib.error.HTTPError as exc:
        console.print(
            f"[yellow]WARNING: server returned HTTP {exc.code} — "
            f"control files are written locally.[/yellow]"
        )
        return False
    except Exception as exc:  # noqa: BLE001
        console.print(
            f"[yellow]WARNING: could not reach wafpass-server ({exc}) — "
            f"control files are written locally.[/yellow]"
        )
        return False

    if status < 300:
        return True
    console.print(
        f"[yellow]WARNING: server returned HTTP {status} — "
        f"control files are written locally.[/yellow]"
    )
    return False


# ── Wizard steps ──────────────────────────────────────────────────────────────


def _step1_description() -> str:
    console.print(Panel("[bold]Step 1 / 7 — Describe the requirement[/bold]"))
    _echo("  Enter a free-text description of what this control should enforce.")
    _echo("  (Multi-line: finish with a blank line)\n")
    lines: list[str] = []
    while True:
        try:
            line = input("  > ")
        except (EOFError, KeyboardInterrupt):
            _echo("\n[yellow]Aborted.[/yellow]")
            sys.exit(0)
        if not line and lines:
            break
        lines.append(line)
    description = "\n".join(lines).strip()
    if not description:
        _echo("[red]Description is required.[/red]")
        return _step1_description()
    return description


def _step2_classify(
    description: str,
    controls_dir: Path,
) -> tuple[str, str, str, list[str]]:
    """Returns (id, pillar, severity, types)."""
    console.print(Panel("[bold]Step 2 / 7 — Classify the control[/bold]"))

    pillar = _select("Select pillar:", PILLARS, default="security")
    suggested_id = _suggest_id(pillar, controls_dir)
    control_id = _prompt(f"Control ID", default=suggested_id).strip().upper()
    severity = _select("Select severity:", SEVERITIES, default="medium")
    types = _multi_select("Select type(s):", TYPES)

    return control_id, pillar, severity, types


def _step3_checks() -> list[WizardCheck]:
    """Interactively build the list of checks."""
    console.print(Panel("[bold]Step 3 / 7 — Define checks[/bold]"))
    checks: list[WizardCheck] = []

    while True:
        _echo(f"\n  [bold]Check #{len(checks) + 1}[/bold]")
        check_id = _prompt("  check id (e.g. tf.region_pinned)")
        engine = _select("  Select engine:", ENGINES, default="terraform")
        check_desc = _prompt("  Description")
        expected = _prompt("  Expected (what passing looks like)")

        checks.append(
            WizardCheck(
                id=check_id,
                engine=engine,  # type: ignore[arg-type]
                description=check_desc,
                expected=expected,
            )
        )
        _echo(f"\n  [green]Check '{check_id}' added.[/green]")
        if not _confirm("Add another check?", default=False):
            break

    return checks


def _step4_preview_edit(control: WizardControl) -> WizardControl:
    """Render YAML, offer [A]ccept / [E]dit / [B]ort."""
    console.print(Panel("[bold]Step 4 / 7 — Preview and edit[/bold]"))

    yaml_text = _control_to_yaml(control)
    console.print(Syntax(yaml_text, "yaml", theme="monokai", line_numbers=False))

    while True:
        try:
            choice = input("\n  [A]ccept / [E]dit / [B]ort: ").strip().lower()
        except (EOFError, KeyboardInterrupt):
            _echo("\n[yellow]Aborted.[/yellow]")
            sys.exit(0)

        if choice in ("a", "accept", ""):
            return control

        if choice in ("b", "abort"):
            _echo("[yellow]Aborted.[/yellow]")
            sys.exit(0)

        if choice in ("e", "edit"):
            editor = os.environ.get("EDITOR", "")
            if editor:
                # Write to temp file, open in $EDITOR, read back
                with tempfile.NamedTemporaryFile(
                    suffix=".yml", mode="w", delete=False, encoding="utf-8"
                ) as tmp:
                    tmp.write(yaml_text)
                    tmp_path = tmp.name
                try:
                    subprocess.run([editor, tmp_path], check=True)
                    edited_text = Path(tmp_path).read_text(encoding="utf-8")
                finally:
                    try:
                        os.unlink(tmp_path)
                    except OSError:
                        pass

                # Strip header comments before parsing
                data_lines = [
                    ln
                    for ln in edited_text.splitlines()
                    if not ln.startswith("# Generated by") and not ln.startswith("# Source:")
                ]
                try:
                    raw = yaml.safe_load("\n".join(data_lines))
                    edited_control = WizardControl.model_validate(raw)
                    console.print(Syntax(_control_to_yaml(edited_control), "yaml", theme="monokai"))
                    return edited_control
                except Exception as exc:  # noqa: BLE001
                    _echo(f"[red]Parse/validation error after edit: {exc}[/red]")
                    _echo("Returning to original draft.")
                    return control
            else:
                _echo(
                    "[yellow]$EDITOR is not set. "
                    "Re-running wizard from Step 1 so you can re-enter values.[/yellow]"
                )
                return _rerun_wizard_from_step1(control)

        _echo("  Please enter A, E, or B.")


def _rerun_wizard_from_step1(current: WizardControl) -> WizardControl:
    """Re-prompt wizard steps 1–3, pre-filling defaults from current control."""
    desc = _step1_description()
    # For step 2 we'll use the existing pillar / severity as defaults inside _step2_classify
    # but we can't easily inject them — just call from scratch
    _echo("[dim](Tip: you can press Enter to keep the suggested defaults)[/dim]")
    control_id, pillar, severity, types = _step2_classify(desc, Path("controls"))
    checks = _step3_checks()
    return WizardControl(
        id=control_id,
        pillar=pillar,  # type: ignore[arg-type]
        severity=severity,  # type: ignore[arg-type]
        type=types,  # type: ignore[arg-type]
        description=desc,
        checks=checks,
    )


def _step5_validate(control: WizardControl) -> tuple[bool, list[str]]:
    """Validate the control and return (ok, error_messages)."""
    console.print(Panel("[bold]Step 5 / 7 — Validate[/bold]"))
    try:
        WizardControl.model_validate(control.model_dump())
        console.print("  [green]✓ Control is valid.[/green]")
        return True, []
    except ValidationError as exc:
        errors = [f"  • {e['loc']}: {e['msg']}" for e in exc.errors()]
        for err in errors:
            console.print(f"  [red]{err}[/red]")
        return False, errors


def _step6_export(
    control: WizardControl,
    controls_dir: Path,
    checkov_dir: Path,
) -> tuple[Path, Path]:
    """Write files and report paths."""
    console.print(Panel("[bold]Step 6 / 7 — Export[/bold]"))
    yaml_path, py_path = export_control(control, controls_dir, checkov_dir)
    console.print(f"  [green]✓ Control YAML written:[/green]  {yaml_path}")
    console.print(f"  [green]✓ Checkov stub written:[/green]  {py_path}")
    return yaml_path, py_path


def _step7_push(control: WizardControl, server_url: str | None) -> None:
    """Optionally push to wafpass-server."""
    console.print(Panel("[bold]Step 7 / 7 — Push to server (optional)[/bold]"))

    effective_url = server_url or os.environ.get("WAFPASS_SERVER_URL", "")
    if effective_url:
        _echo(f"  Server: {effective_url}")
    else:
        _echo("  (No server URL configured; set WAFPASS_SERVER_URL or use --server-url)")

    if not _confirm("Push to wafpass-server?", default=bool(effective_url)):
        _echo("  [dim]Skipped.[/dim]")
        return

    if not effective_url:
        effective_url = _prompt("  Enter server URL")

    ok = push_to_server(control, effective_url)
    if ok:
        console.print("  [green]✓ Control pushed to server.[/green]")


# ── Public entry points ───────────────────────────────────────────────────────


def run_wizard(
    controls_dir: Path,
    checkov_dir: Path,
    server_url: str | None = None,
) -> WizardControl | None:
    """Run the full interactive wizard.  Returns the validated control, or None."""
    console.print(
        Panel(
            "[bold cyan]wafpass control generate[/bold cyan]\n"
            "Interactive wizard — author a new WAF++ control",
            expand=False,
        )
    )

    # Step 1
    description = _step1_description()

    # Step 2
    control_id, pillar, severity, types = _step2_classify(description, controls_dir)

    # Step 3
    checks = _step3_checks()

    control = WizardControl(
        id=control_id,
        pillar=pillar,  # type: ignore[arg-type]
        severity=severity,  # type: ignore[arg-type]
        type=types,  # type: ignore[arg-type]
        description=description,
        checks=checks,
    )

    # Step 4 — may return an edited control
    control = _step4_preview_edit(control)

    # Step 5 — validate; block export on errors
    ok, errors = _step5_validate(control)
    if not ok:
        console.print("[red]Export blocked until validation passes. Fix errors and re-run.[/red]")
        return None

    # Step 6
    _step6_export(control, controls_dir, checkov_dir)

    # Step 7
    _step7_push(control, server_url)

    console.print("\n[bold green]Done![/bold green]  Control authored successfully.")
    return control


def run_wizard_non_interactive(
    spec_path: Path,
    controls_dir: Path,
    checkov_dir: Path,
    server_url: str | None = None,
) -> WizardControl | None:
    """Non-interactive mode: load spec from JSON/YAML, validate, export, push."""
    if not spec_path.exists():
        console.print(f"[red]Spec file not found: {spec_path}[/red]")
        return None

    raw_text = spec_path.read_text(encoding="utf-8")
    suffix = spec_path.suffix.lower()

    try:
        if suffix in (".yaml", ".yml"):
            raw = yaml.safe_load(raw_text)
        else:
            raw = json.loads(raw_text)
    except Exception as exc:  # noqa: BLE001
        console.print(f"[red]Failed to parse spec file: {exc}[/red]")
        return None

    try:
        control = WizardControl.model_validate(raw)
    except ValidationError as exc:
        console.print("[red]Spec file validation errors:[/red]")
        for e in exc.errors():
            console.print(f"  • {e['loc']}: {e['msg']}")
        return None

    console.print(f"[green]✓ Spec loaded and validated:[/green] {control.id}")

    yaml_path, py_path = export_control(control, controls_dir, checkov_dir)
    console.print(f"[green]✓ Control YAML:[/green]  {yaml_path}")
    console.print(f"[green]✓ Checkov stub:[/green]  {py_path}")

    effective_url = server_url or os.environ.get("WAFPASS_SERVER_URL", "")
    if effective_url:
        ok = push_to_server(control, effective_url)
        if ok:
            console.print(f"[green]✓ Pushed to server:[/green] {effective_url}")

    return control
